version: 2.1

orbs:
  python: circleci/python@1.3

jobs:
  build-and-test-python: &build-and-test-python
    executor:
      name: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
  build-and-test-python-3-7:
    <<: *build-and-test-python
    executor:
      name: python/default
      tag: "3.7"
  build-and-test-python-3-8:
    <<: *build-and-test-python
    executor:
      name: python/default
      tag: "3.8"
  build-and-test-python-3-9:
    <<: *build-and-test-python
    executor:
      name: python/default
      tag: "3.9"
  build-and-test-python-3-10:
    name: "HI"
    <<: *build-and-test-python
    executor:
      name: python/default
      tag: "3.10"

workflows:
  main:
    jobs:
      - build-and-test-python-3-7
      - build-and-test-python-3-8
      - build-and-test-python-3-9
      - build-and-test-python-3-10
