version: 2.1

orbs:
  python: circleci/python@1.3

jobs:
  .build-and-test-python: &build-and-test-python
    parameters:
      pyver:
        description: "Python Version"
        type: string
    executor:
      name: python/default
      tag: << parameters.pyver >>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
  build-and-test-python-37:
    <<: *build-and-test-python
  build-and-test-python-38:
    <<: *build-and-test-python

workflows:
  main:
    jobs:
      - build-and-test-python-37:
          pyver: "3.7"
      - build-and-test-python-38:
          pyver: "3.8"
