version: 2.1

orbs:
  python: circleci/python@1.3

jobs:
  build-and-test-python-3-7:
    executor:
      name: python/default
      tag: "3.7"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry

workflows:
  main:
    jobs:
      - build-and-test-python-3-7
