version: 2.1

orbs:
  python: circleci/python@1.3

jobs:
  build-and-test-python-variable:
    parameters:
      pyver:
        description: "Python Version"
        type: string
    executor:
      name: python/default
      tag: << parameters.pyver >>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry

workflows:
  main:
    jobs:
      - build-and-test-python-3-7:
          pyver: "3.7"
      - build-and-test-python-3-8
          pyver: "3.8"
